title: Maria Sim천es
email: contact@mariasimoes.arq.br
description: > 
  Architecture Student
permalink: ':title/'
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Maria Sim천es
author-pic: profile.jpg
about-author: My name is Maria Sim천es and I am an Architecture and Urban Planning student at the Federal University of Rio de Janeiro.

email: contact@mariasimoes.arq.br
website: mariasimoes.arq.br
linkedin: mesim천es

analytics: # Google Analytics

paginate: 6
paginate_path: /page:num/

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]